#!/bin/sh
xrandr --output DisplayPort-1 --off --output DisplayPort-0 --off --output DVI-0 --mode samsungSyncmaster --pos 1920x256 --rotate normal --output HDMI-0 --mode 1920x1080 --pos 0x200 --rotate normal
SCRIPT_PATH=`readlink -f "$0"`
ln -f -s "$SCRIPT_PATH" `dirname "$SCRIPT_PATH"`/monitorLastSetup
